name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'
  workflow_call:
 
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Create NuGet Config
      run: |
        dotnet nuget add source --name github --username OwenChen2024113 --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text https://nuget.pkg.github.com/OwenChen2024113/index.json

    - name: Restore dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
        
    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack
      run: dotnet pack --configuration Release --no-build -o ./nupkg

    - name: Publish
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.PACKAGE_TOKEN }}
