name: Publish NuGet package

on:
  push:
    tags:
      - 'v*'
  workflow_call:
      secrets:
        PACKAGE_TOKEN:
          required: true
        USE_PACKAGE_TOKEN:
          required: true
 
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: Configure NuGet
      run: dotnet nuget add source --username OwenChen2024113 --password ${{ secrets.PACKAGE_TOKEN }} --store-password-in-clear-text --name github https://nuget.pkg.github.com/OwenChen2024113/index.json

    - name: Restore dependencies
      run: dotnet restore
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test  --logger "trx;LogFileName=test-results.trx" || true

    - name: Test Report
      uses: dorny/test-reporter@v1
      if: always()
      with:
        name: DotNET Tests
        path: "**/test-results.trx"                            
        reporter: dotnet-trx
        fail-on-error: true

    - name: Pack
      run: dotnet pack --configuration Release --no-build -o ./nupkg

    - name: Publish
      run: dotnet nuget push ./nupkg/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.PACKAGE_TOKEN }}
